### ISSUE TITLE
converting posteriors (treatment effects) into Cohen's d

### ISSUE THREAD

**Issue by ericpgreen** [ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse#31]
Hey @ASKurz. It looks to me like the [bookdown Chapter 19 ](https://bookdown.org/ajkurz/DBDA_recoded/metric-predicted-variable-with-one-nominal-predictor.html#hierarchical-bayesian-approach) differs from the [Chapter 19 Rmd](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/blob/master/19.Rmd). Is that true? I was looking for advice on converting posteriors into Cohen's d and google brought me to your github page. I moved over to the bookdown text online but did not see the same references to cohen there that I found in the Rmd.

**Comment by ASKurz** [comment]
Hey Eric,

Kinda. It looks like you're using a link to the 0.0.5 version ([https://bookdown.org/ajkurz/DBDA_recoded/](https://bookdown.org/ajkurz/DBDA_recoded/)). The current version is 0.3.0 ([https://bookdown.org/content/3686/](https://bookdown.org/content/3686/)). Unfortunately, this is one of a few ebooks I initially released under my old UM email, which I no longer have access to. Without access to that email, I'm not aware of a way to convert or otherwise remove these old links. But anyways, the [https://bookdown.org/content/3686/](https://bookdown.org/content/3686/) link is associated with my permanent email and it should always have the current version.

**Comment by ericpgreen** [comment]
Thanks! Google was just leading me down the wrong path. Great chapter!

**Comment by ASKurz** [comment]
Thanks for the kind words. After glancing at the content of Chapter 19, it looks like I'll need to update the way I compute the pooled standard deviation. One can find better definitions [here](https://www.statisticshowto.com/pooled-standard-deviation/). Always learning...

**Comment by ericpgreen** [comment]
I appreciate the tip...and I hear you. I feel like I am revisiting ideas that I thought I crossed off as "learned" but now...

1. [Standardizing in the context of repeated measures](https://easystats.github.io/effectsize/articles/standardize_data.html)
2. [Standardized differences vs Cohen's d](https://easystats.github.io/effectsize/articles/standardize_parameters.html) ([and as applied to Bayesian models](https://easystats.github.io/effectsize/articles/bayesian_models.html))

And still digesting [this approach](https://www.barelysignificant.com/phd_thesis/appendix-brms.html#inference-and-conclusions) to calculating cohen's d in the Bayesian context.

Always learning...
